<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Aetherbound.Utils.SqlSave</PackageId>
    <Version>0.0.5</Version>
    <Authors>Tyler Long</Authors>
    <Company>Aetherbound Studios</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GodotSharp" Version="4.7.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>

</Project>
